pinger:
  verbose: true
  delay: 60
  hosts:
    - https://google.com
    - https://arpa.net
  mail:
    smtp:
      hostname: 'smtp.mailtrap.io'
      port: 2525
      username: 'xxx'
      password: 'yyy'
      auth: 'login'
    credentials:
      from: Pinger Sender <from@smtp.mailtrap.io>
      to: Pinger Receiver <to@smtp.mailtrap.io>
      subject: Servers state!
